"""littlecar2 的直接调用视觉算法。"""

from .advance_yolo import (
    CAMERA_INDEX_COLOR_CIRCLE,
    CAMERA_INDEX_QR,
    advance_detect_circle,
    advance_detect_color,
    advance_detect_color_hsv,
    advance_detect_color_hybrid,
    reset_advance_tracking,
)
from .hybrid_color import (
    DEFAULT_HSV_CONFIG_PATH,
    EMPTY_SLOT_TYPE,
    HSV_UNCERTAIN_POLICY,
    detect_color_hybrid,
    get_hsv_config,
    refine_yolo_detection_with_hsv,
)
from .hsv_color import (
    HSVClassification,
    HSVColorProfile,
    HSVConfig,
    HSVProcessingConfig,
    HSVRange,
    HSVSamplingConfig,
    HSVSampleRegion,
    build_all_color_masks,
    build_color_mask,
    build_color_mask_from_hsv,
    classify_bbox_hsv,
    classify_color_hsv,
    classify_roi_hsv,
    compute_sample_bbox,
    build_hsv_sample_region,
    detect_color_hsv,
    load_hsv_config,
    save_hsv_config,
)
from .materials import advance_detect_disk_center, detect_disk_center
from .preview import render_camera_preview
from .qr import QR_CONFIRM_COUNT, QR_MISSING_THRESHOLD, QR_WINDOW_SIZE, advance_detect_qr, detect_qr, reset_qr_tracking
from .yolo import configure_model_backend, detect_circle, detect_color, get_model_backend, validate_engine_runtime

__all__ = [
    "detect_circle",
    "detect_color",
    "detect_color_hsv",
    "classify_color_hsv",
    "HSVRange",
    "HSVColorProfile",
    "HSVProcessingConfig",
    "HSVSamplingConfig",
    "HSVSampleRegion",
    "HSVConfig",
    "HSVClassification",
    "load_hsv_config",
    "save_hsv_config",
    "build_color_mask",
    "build_color_mask_from_hsv",
    "build_all_color_masks",
    "compute_sample_bbox",
    "build_hsv_sample_region",
    "classify_bbox_hsv",
    "classify_roi_hsv",
    "configure_model_backend",
    "get_model_backend",
    "validate_engine_runtime",
    "detect_disk_center",
    "render_camera_preview",
    "advance_detect_circle",
    "advance_detect_color",
    "advance_detect_color_hsv",
    "advance_detect_color_hybrid",
    "detect_color_hybrid",
    "refine_yolo_detection_with_hsv",
    "get_hsv_config",
    "DEFAULT_HSV_CONFIG_PATH",
    "EMPTY_SLOT_TYPE",
    "HSV_UNCERTAIN_POLICY",
    "advance_detect_disk_center",
    "reset_advance_tracking",
    "CAMERA_INDEX_COLOR_CIRCLE",
    "CAMERA_INDEX_QR",
    "detect_qr",
    "advance_detect_qr",
    "reset_qr_tracking",
    "QR_WINDOW_SIZE",
    "QR_CONFIRM_COUNT",
    "QR_MISSING_THRESHOLD",
]
