"""STM32 与 Jetson 视觉服务共用的命令和状态常量。"""

HEADER = b"\x5A\xA5"
MAX_PAYLOAD_LEN = 255

CMD_START_COLOR = 0x01
CMD_START_CIRCLE = 0x02
CMD_START_DISK_CENTER = 0x03
CMD_STOP = 0x04
CMD_START_QR = 0x05

CMD_ACK = 0x80
CMD_COLOR_RESULT = 0x81
CMD_CIRCLE_RESULT = 0x82
CMD_DISK_CENTER_RESULT = 0x83
CMD_QR_RESULT = 0x84

TASK_CODE_LENGTH = 15

ACK_OK = 0
ACK_BAD_CMD = 1
ACK_BAD_LENGTH = 2
ACK_BAD_PERIOD = 3

DISK_CENTER_NO_TARGET = 0
DISK_CENTER_OK = 1

START_COMMANDS = (CMD_START_COLOR, CMD_START_CIRCLE, CMD_START_DISK_CENTER, CMD_START_QR)
