"""Generate deterministic STM32 C task functions from a map plan."""
from __future__ import annotations
import math
import re
from .models import ContinuousPathSegment, Plan, RotateInPlace, Waypoint

class CodeGenerationError(ValueError):
    """Raised when a plan cannot be represented by the blocking STM32 API."""

_TASK_NAME = re.compile(r"^Task_[A-Za-z_][A-Za-z0-9_]*$")

def _safe_comment(value: object) -> str:
    return str(value).replace("\r", " ").replace("\n", " ").replace("/*", "/ *").replace("*/", "* /")

def default_task_function_name(plan_name: str) -> str:
    stem = re.sub(r"_+", "_", "".join(c if c.isascii() and c.isalnum() else "_" for c in str(plan_name))).strip("_") or "Plan"
    return f"Task_{'Plan_' if stem[0].isdigit() else ''}{stem}"

def validate_task_function_name(function_name: str) -> None:
    if not _TASK_NAME.fullmatch(function_name): raise CodeGenerationError("函数名称必须符合 Task_<Name> 格式。")

def format_c_float(value: float) -> str:
    number = float(value)
    if not math.isfinite(number): raise CodeGenerationError("C 浮点常量不能是 NaN 或 Infinity。")
    if number == 0.0: return "0.0f"
    rendered = format(number, ".9f").rstrip("0").rstrip(".")
    return f"{rendered if '.' in rendered else rendered + '.0'}f"

def _finite(value: float, label: str, step: int) -> None:
    if not math.isfinite(float(value)): raise CodeGenerationError(f"步骤 {step} 的 {label} 必须是有限数值。")

def validate_plan_for_blocking_codegen(plan: Plan) -> list[str]:
    if not plan.steps: raise CodeGenerationError("当前方案没有任何运动步骤。")
    current_x = current_y = current_yaw = 0.0
    for index, step in enumerate(plan.steps, 1):
        if isinstance(step, Waypoint):
            for value, label in ((step.x_mm, "X 坐标"), (step.y_mm, "Y 坐标"), (step.yaw_deg, "航向角"), (step.dwell_s, "停留时间")): _finite(value, label, index)
            if not step.use_yaw or not step.stop or step.dwell_s < 0: raise CodeGenerationError(f"步骤 {index} 的 GOTO 语义不受阻塞接口支持。")
            current_x, current_y, current_yaw = step.x_mm, step.y_mm, step.yaw_deg
        elif isinstance(step, RotateInPlace):
            _finite(step.yaw_deg, "航向角", index)
            current_yaw = step.yaw_deg
        elif isinstance(step, ContinuousPathSegment):
            if len(step.points) < 2: raise CodeGenerationError(f"步骤 {index} 的连续路径至少需要两个点。")
            first = step.points[0]
            if (not math.isclose(first.x_mm, current_x, abs_tol=1e-6)
                    or not math.isclose(first.y_mm, current_y, abs_tol=1e-6)
                    or not math.isclose(first.yaw_deg, current_yaw, abs_tol=1e-6)):
                raise CodeGenerationError(f"步骤 {index} 的入口点必须与上一动作终点一致。")
            for point_index, point in enumerate(step.points):
                for value, label in ((point.x_mm, "X 坐标"), (point.y_mm, "Y 坐标"), (point.yaw_deg, "航向角")): _finite(value, label, index)
                if point_index and math.hypot(point.x_mm - step.points[point_index-1].x_mm, point.y_mm - step.points[point_index-1].y_mm) < 1.0:
                    raise CodeGenerationError(f"步骤 {index} 的连续路径相邻点距离必须至少为 1 mm。")
            current_x, current_y, current_yaw = step.points[-1].x_mm, step.points[-1].y_mm, step.points[-1].yaw_deg
        else: raise CodeGenerationError(f"步骤 {index} 使用了不支持的动作类型。")
    return []

def _goto_block(x: float, y: float, yaw: float) -> list[str]:
    return ["    if (AdvanceMotion_GotoPoseBlocking(", f"            {format_c_float(x)},", f"            {format_c_float(y)},", f"            {format_c_float(yaw)},", "            CHASSIS_DEFAULT_ACC) != ADVANCE_MOTION_STATE_ARRIVED)", "    {", "        AdvanceMotion_Cancel();", "        return;", "    }"]

def generate_task_function(plan: Plan, function_name: str) -> str:
    validate_task_function_name(function_name); validate_plan_for_blocking_codegen(plan)
    lines = ["/*", f" * Plan: {_safe_comment(plan.name)}", " * Generated by LittleCar2 map planner.", " */", f"void {function_name}(void)", "{"]
    current_x = current_y = 0.0
    for index, step in enumerate(plan.steps, 1):
        lines.append("")
        if isinstance(step, Waypoint):
            lines += [f"    /* {index}. GOTO */", *_goto_block(step.x_mm, step.y_mm, step.yaw_deg)]
            delay = round(step.dwell_s * 1000)
            if delay: lines.append(f"    HAL_Delay({delay}U);")
            current_x, current_y = step.x_mm, step.y_mm
        elif isinstance(step, RotateInPlace):
            lines += [f"    /* {index}. ROTATE */", *_goto_block(current_x, current_y, step.yaw_deg)]
        else:
            name = f"path_{index}"
            lines.append(f"    static const AdvanceMotion_PathPoint_t {name}[] = {{")
            lines += [f"        {{{format_c_float(p.x_mm)}, {format_c_float(p.y_mm)}, {format_c_float(p.yaw_deg)}}}," for p in step.points]
            lines += ["    };", f"    /* {index}. FOLLOW PATH */", f"    if (AdvanceMotion_FollowPathBlocking({name}, sizeof({name}) / sizeof({name}[0])) != ADVANCE_MOTION_STATE_ARRIVED)", "    {", "        AdvanceMotion_Cancel();", "        return;", "    }"]
            current_x, current_y = step.points[-1].x_mm, step.points[-1].y_mm
    return "\n".join([*lines, "}", ""])
