#ifndef __ADVANCE_MOTION_CONFIG_H__
#define __ADVANCE_MOTION_CONFIG_H__

#include <stdint.h>

/*
 * 由 motion_workbench 从 STM32 当前活动参数导出。
 *
 * PID revision: 4
 * Path revision: 0
 *
 * 将本文件复制到 Core/Inc/advance_motion_config.h，
 * 然后重新编译并烧录 STM32。
 */

/* 单点位姿 PID。 */
#define ADVANCE_MOTION_DEFAULT_KP_POS (1.36000001f)
#define ADVANCE_MOTION_DEFAULT_KI_POS (0.140000001f)
#define ADVANCE_MOTION_DEFAULT_KD_POS (0.910000026f)
#define ADVANCE_MOTION_DEFAULT_KP_YAW (2.55999994f)
#define ADVANCE_MOTION_DEFAULT_KI_YAW (1.0f)
#define ADVANCE_MOTION_DEFAULT_KD_YAW (0.800000012f)

/* 连续路径横向与航向 PD。 */
#define ADVANCE_MOTION_PATH_KP_POS (0.980000019f)
#define ADVANCE_MOTION_PATH_KD_VEL (0.620000005f)
#define ADVANCE_MOTION_PATH_KP_YAW (1.41999996f)
#define ADVANCE_MOTION_PATH_KD_YAW (0.426999986f)

/* 连续路径速度规划。 */
#define ADVANCE_MOTION_PATH_CRUISE_SPEED_MM_S (820.0f)
#define ADVANCE_MOTION_PATH_MAX_WZ_DEG_S (100.0f)
#define ADVANCE_MOTION_PATH_ACCEL_MM_S2 (800.0f)
#define ADVANCE_MOTION_PATH_DECEL_MM_S2 (1000.0f)
#define ADVANCE_MOTION_PATH_MAX_LATERAL_ACC_MM_S2 (600.0f)

/* 曲率预览与法向前馈。 */
#define ADVANCE_MOTION_PATH_CURVATURE_PREVIEW_MM (300.0f)
#define ADVANCE_MOTION_PATH_CURVATURE_FF_TIME_S (0.0500000007f)

/* 动态前视。 */
#define ADVANCE_MOTION_PATH_LOOKAHEAD_MIN_MM (60.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_BASE_MM (60.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_SPEED_GAIN_S (0.150000006f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_CURVE_GAIN_MM (120.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_MAX_MM (180.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_RATE_MM_S (400.0f)
#define ADVANCE_MOTION_PATH_INITIAL_LOOKAHEAD_MM (80.0f)

/* 末段捕获。 */
#define ADVANCE_MOTION_PATH_FINAL_CAPTURE_DISTANCE_MM (60.0f)
#define ADVANCE_MOTION_PATH_FINAL_CAPTURE_SPEED_MM_S (150.0f)

/* 组合 GOTO 默认策略。 */
#define ADVANCE_MOTION_DEFAULT_LARGE_YAW_ALIGN_ENABLE ((uint8_t)0U)

#endif
