#ifndef __ADVANCE_MOTION_CONFIG_H__
#define __ADVANCE_MOTION_CONFIG_H__

#include <stdint.h>

#define ADVANCE_MOTION_CONFIG_SCHEMA_VERSION ((uint32_t)1U)

/* 单点位姿 PID。 */
#define ADVANCE_MOTION_DEFAULT_KP_POS (1.5f)
#define ADVANCE_MOTION_DEFAULT_KI_POS (0.10f)
#define ADVANCE_MOTION_DEFAULT_KD_POS (0.78f)
#define ADVANCE_MOTION_DEFAULT_KP_YAW (2.50f)
#define ADVANCE_MOTION_DEFAULT_KI_YAW (1.0f)
#define ADVANCE_MOTION_DEFAULT_KD_YAW (0.80f)

/* 连续路径横向与航向 PD。 */
#define ADVANCE_MOTION_PATH_KP_POS (0.98f)
#define ADVANCE_MOTION_PATH_KD_VEL (0.620f)
#define ADVANCE_MOTION_PATH_KP_YAW (1.42f)
#define ADVANCE_MOTION_PATH_KD_YAW (0.427f)

/* 连续路径速度规划。 */
#define ADVANCE_MOTION_PATH_CRUISE_SPEED_MM_S (820.0f)
#define ADVANCE_MOTION_PATH_MAX_WZ_DEG_S (100.0f)
#define ADVANCE_MOTION_PATH_ACCEL_MM_S2 (800.0f)
#define ADVANCE_MOTION_PATH_DECEL_MM_S2 (1000.0f)
#define ADVANCE_MOTION_PATH_MAX_LATERAL_ACC_MM_S2 (600.0f)

/* 曲率预览与法向前馈。 */
#define ADVANCE_MOTION_PATH_CURVATURE_PREVIEW_MM (300.0f)
#define ADVANCE_MOTION_PATH_CURVATURE_FF_TIME_S (0.05f)

/* 动态前视。 */
#define ADVANCE_MOTION_PATH_LOOKAHEAD_MIN_MM (60.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_BASE_MM (60.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_SPEED_GAIN_S (0.15f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_CURVE_GAIN_MM (120.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_MAX_MM (180.0f)
#define ADVANCE_MOTION_PATH_LOOKAHEAD_RATE_MM_S (400.0f)
#define ADVANCE_MOTION_PATH_INITIAL_LOOKAHEAD_MM (80.0f)

/* 末段捕获。 */
#define ADVANCE_MOTION_PATH_FINAL_CAPTURE_DISTANCE_MM (60.0f)
#define ADVANCE_MOTION_PATH_FINAL_CAPTURE_SPEED_MM_S (150.0f)

/* 组合 GOTO 默认策略。 */
#define ADVANCE_MOTION_DEFAULT_LARGE_YAW_ALIGN_ENABLE ((uint8_t)0U)

#endif
